# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Md Aamir Raihan
tagline:          'A Dreamer'
description:      ''
url:              https://aamirraihan.github.io

author:
  name:           'Md Aamir Raihan'
  url:            https://twitter.com/aamirraihan

paginate:         5

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "CV"
   link: "../cv.pdf"
 - name: "Contact"
   link: "../contact"

# Custom vars
version:          1.0.0

github:
  repo:           https://aamirraihan.github.io

